'''
Created on Apr 21, 2012

@author: quandtan
'''

class KeyEnum(object):
    
    BASEDIR = 'BASEDIR'
    CREATED_FILES = 'CREATED_FILES'
    COLLECTOR = 'COLLECTORS'
    COMMENT = 'COMMENT'
    DATASET_CODE = 'DATASET_CODE'
    FILE_IDX = 'FILE_IDX'
    GENERATOR = 'GENERATORS'
    INPUT = 'INPUTS'
    JOB_IDX = 'JOB_IDX' 
    LOG_LEVEL = 'LOG_LEVEL'
    MZML = 'MZML'
    MZXML = 'MZXML'
    NAME = 'NAME'
    OUTPUT = 'OUTPUT'      
    PARAM_IDX = 'PARAM_IDX'
    PREFIX = 'PREFIX'
    TEMPLATE = 'TEMPLATE'
    STORAGE = 'STORAGE'
    WORKDIR = 'WORKDIR'
    SOURCE = 'SOURCE'
    DESTINATION = 'DESTINATION'